function features = extractFeatures(preprocessedData)
    accelData = preprocessedData.accel;
    gyroData = preprocessedData.gyro;
    
    % Initialize feature struct
    features = struct;
    
    % Feature extraction function
    extractStatFeatures = @(data) struct( ...
        'mean', mean(data, 2), ...
        'std', std(data, 0, 2), ...
        'rms', rms(data, 2), ...
        'max', max(data, [], 2), ...
        'min', min(data, [], 2), ...
        'energy', sum(data .^ 2, 2));
    
    % Extract features for accelerometer data
    features.accel = extractStatFeatures(accelData);
    
    % Extract features for gyroscope data
    features.gyro = extractStatFeatures(gyroData);
    
    % Calculate correlations between accelerometer and gyroscope data
    features.corr = struct( ...
        'accel_gyro_x', corr(accelData(1, :)', gyroData(1, :)'), ...
        'accel_gyro_y', corr(accelData(2, :)', gyroData(2, :)'), ...
        'accel_gyro_z', corr(accelData(3, :)', gyroData(3, :)'));
end
